services:
  redis:
    image: redis:latest
    container_name: redis
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - ./buildfiles/redis.conf:/usr/local/etc/redis/redis.conf
    restart: on-failure
    ports:
      - "6378:6379"
    env_file:
      - .env
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_dump.sql:/app/init_dump.sql
    restart: on-failure
    ports:
      - "5433:5432"
  bot:
    build:
      context: .
      dockerfile: buildfiles/Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - redis


volumes:
  pgdata:
