services:
  redis:
    build:
      context: buildfiles
      dockerfile: redis.dockerfile
    env_file:
      - .env
    restart: on-failure
    ports:
      - "6378:6379"
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_dump.sql:/app/init_dump.sql
    restart: on-failure
    ports:
      - "5433:5432"
  bot:
    build:
      context: .
      dockerfile: buildfiles/Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - redis


volumes:
  pgdata:
