"""Add column in referrals 

Revision ID: 72f8b3558c9a
Revises: de5c3e77df32
Create Date: 2024-10-09 13:01:49.804828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f8b3558c9a'
down_revision: Union[str, None] = 'de5c3e77df32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('telegram_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'telegram_id')
    # ### end Alembic commands ###
