"""Rename column

Revision ID: af193fd921d9
Revises: 52b68521f9c7
Create Date: 2024-10-12 21:07:41.060894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af193fd921d9'
down_revision: Union[str, None] = '52b68521f9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('user_telegram_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('uq_user_bookmaker', 'referrals', type_='unique')
    op.create_unique_constraint('uq_user_bookmaker', 'referrals', ['user_telegram_id', 'bookmaker_id'])
    op.drop_constraint('fk_referrals_telegram_id_users', 'referrals', type_='foreignkey')
    op.create_foreign_key(op.f('fk_referrals_user_telegram_id_users'), 'referrals', 'users', ['user_telegram_id'], ['telegram_id'])
    op.drop_column('referrals', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_referrals_user_telegram_id_users'), 'referrals', type_='foreignkey')
    op.create_foreign_key('fk_referrals_telegram_id_users', 'referrals', 'users', ['telegram_id'], ['telegram_id'])
    op.drop_constraint('uq_user_bookmaker', 'referrals', type_='unique')
    op.create_unique_constraint('uq_user_bookmaker', 'referrals', ['telegram_id', 'bookmaker_id'])
    op.drop_column('referrals', 'user_telegram_id')
    # ### end Alembic commands ###
