"""Initial migratio n

Revision ID: beb99d940174
Revises: 
Create Date: 2024-10-06 21:51:00.220903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb99d940174'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmakers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookmakers')),
    sa.UniqueConstraint('name', name=op.f('uq_bookmakers_name'))
    )
    op.create_table('streamers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_streamers')),
    sa.UniqueConstraint('name', name=op.f('uq_streamers_name'))
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('language_code', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMINISTRATOR', name='role'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_users_telegram_id'))
    )
    op.create_table('referrals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('streamer_id', sa.Integer(), nullable=False),
    sa.Column('referral_key', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], name=op.f('fk_referrals_bookmaker_id_bookmakers')),
    sa.ForeignKeyConstraint(['streamer_id'], ['streamers.id'], name=op.f('fk_referrals_streamer_id_streamers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_referrals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals')),
    sa.UniqueConstraint('referral_key', name=op.f('uq_referrals_referral_key')),
    sa.UniqueConstraint('user_id', 'bookmaker_id', name='uq_user_bookmaker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referrals')
    op.drop_table('users')
    op.drop_table('streamers')
    op.drop_table('bookmakers')
    # ### end Alembic commands ###
