name: "Docker CI/CD"


on:
  push:
    branches:
      - 'main'


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: List files in the current directory
        run: ls -R

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./buildfiles
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/telegram-betbot:latest